In [1]:
import pandas as pd

In [28]:
df_7 = pd.read_csv("df_7.csv").iloc[:, 1:]
df_7.head()

,CODMUN,AREAMUN,AFECBLAN,AFECGRIS,KM2BLAN,KM2GRIS,PRMUNZB,PRMUNZG,POB21_ZB,CUEN_ZB,PRPZB21,Shape_Length,Shape_Area,POB21_ZG,CUEN_ZG,CBMAS30,CBMAS100,COB3G,COB4G
0,33024,182.147589,SI,NO,3.507827,0,1.925816,0.000000,4799,47,1.76749,78932.255594,1.821476e+08,0,0,0.66,0.00,1.0,1.0
1,33042,5.709173,SI,NO,0.331474,0,5.805987,0.000000,0,0,0.00000,17626.648411,5.709173e+06,0,0,0.00,0.00,1.0,1.0
2,24089,39.004137,SI,NO,0.001086,0,0.002784,0.000000,0,0,0.00000,34958.056216,3.900414e+07,0,0,1.00,1.00,1.0,1.0
3,37274,39.470838,NO,SI,0.000000,0,0.000000,0.017437,0,0,0.00000,42267.793272,3.947084e+07,0,0,1.00,1.00,1.0,1.0
4,39085,24.582482,SI,NO,0.000103,0,0.000417,0.000000,0,0,0.00000,24863.966554,2.458248e+07,0,0,0.99,0.62,1.0,1.0

In [30]:
df_7["AFECBLAN"] = [1 if x == "SI" else 0 for x in df_7["AFECBLAN"]]
df_7["AFECGRIS"] = [1 if x == "SI" else 0 for x in df_7["AFECGRIS"]]

In [25]:
df_7.head()

,CODMUN,AREAMUN,AFECBLAN,AFECGRIS,KM2BLAN,KM2GRIS,PRMUNZB,PRMUNZG,POB21_ZB,CUEN_ZB,PRPZB21,Shape_Length,Shape_Area,POB21_ZG,CUEN_ZG,CBMAS30,CBMAS100,COB3G,COB4G
0,33024,182.147589,0,0,3.507827,0,1.925816,0.000000,4799,47,1.76749,78932.255594,1.821476e+08,0,0,0.66,0.00,1.0,1.0
1,33042,5.709173,0,0,0.331474,0,5.805987,0.000000,0,0,0.00000,17626.648411,5.709173e+06,0,0,0.00,0.00,1.0,1.0
2,24089,39.004137,0,0,0.001086,0,0.002784,0.000000,0,0,0.00000,34958.056216,3.900414e+07,0,0,1.00,1.00,1.0,1.0
3,37274,39.470838,0,1,0.000000,0,0.000000,0.017437,0,0,0.00000,42267.793272,3.947084e+07,0,0,1.00,1.00,1.0,1.0
4,39085,24.582482,0,0,0.000103,0,0.000417,0.000000,0,0,0.00000,24863.966554,2.458248e+07,0,0,0.99,0.62,1.0,1.0

In [31]:
df_7 = df_7.drop(["Shape_Length", "Shape_Area", "CUEN_ZB"], axis = 1)
df_7.head()

,CODMUN,AREAMUN,AFECBLAN,AFECGRIS,KM2BLAN,KM2GRIS,PRMUNZB,PRMUNZG,POB21_ZB,PRPZB21,POB21_ZG,CUEN_ZG,CBMAS30,CBMAS100,COB3G,COB4G
0,33024,182.147589,0,0,3.507827,0,1.925816,0.000000,4799,1.76749,0,0,0.66,0.00,1.0,1.0
1,33042,5.709173,0,0,0.331474,0,5.805987,0.000000,0,0.00000,0,0,0.00,0.00,1.0,1.0
2,24089,39.004137,0,0,0.001086,0,0.002784,0.000000,0,0.00000,0,0,1.00,1.00,1.0,1.0
3,37274,39.470838,0,0,0.000000,0,0.000000,0.017437,0,0.00000,0,0,1.00,1.00,1.0,1.0
4,39085,24.582482,0,0,0.000103,0,0.000417,0.000000,0,0.00000,0,0,0.99,0.62,1.0,1.0

In [11]:
df_12 = pd.read_csv("df_12.csv").iloc[:, 1:]
df_12.head()

,codMuni,NHOSPI,NFARMA,NCENTEDUC,NATURGHOSP,NATPRIMARIA,DISTHOSPIT,DISTFARMA,DISTCEDUC,DISTCURGH,DISTATPRIM
0,24089,5,31.0,70.0,4.0,11.0,1.704359,1.532529,1.262780,1.741295,1.041060
1,33024,8,49.0,252.0,11.0,15.0,4.736787,4.356865,1.769208,4.704072,3.419300
2,33042,0,1.0,4.0,1.0,1.0,8.030180,1.809500,1.696439,2.114355,1.908441
3,37274,3,88.0,232.0,2.0,12.0,2.267347,0.901499,0.745695,1.861151,1.057718
4,39035,1,7.0,18.0,1.0,1.0,2.266143,1.108265,1.129460,1.590444,1.535823

In [16]:
df_12 = df_12.rename({'codMuni':'CODMUN'}, axis=1)
df_12

,CODMUN,NHOSPI,NFARMA,NCENTEDUC,NATURGHOSP,NATPRIMARIA,DISTHOSPIT,DISTFARMA,DISTCEDUC,DISTCURGH,DISTATPRIM
0,24089,5,31.0,70.0,4.0,11.0,1.704359,1.532529,1.262780,1.741295,1.041060
1,33024,8,49.0,252.0,11.0,15.0,4.736787,4.356865,1.769208,4.704072,3.419300
2,33042,0,1.0,4.0,1.0,1.0,8.030180,1.809500,1.696439,2.114355,1.908441
3,37274,3,88.0,232.0,2.0,12.0,2.267347,0.901499,0.745695,1.861151,1.057718
4,39035,1,7.0,18.0,1.0,1.0,2.266143,1.108265,1.129460,1.590444,1.535823
5,39075,4,45.0,152.0,2.0,12.0,1.894518,1.031038,0.673276,1.849598,0.984715
6,39085,0,2.0,4.0,1.0,1.0,6.086627,2.111812,2.176340,2.249691,1.682296
7,48020,10,159.0,212.0,6.0,24.0,1.665895,0.750482,0.746963,1.605614,0.934283

In [12]:
df_estructura = pd.read_csv("df_estructura.csv").iloc[:, 1:]
df_estructura.head()

,CODMUNI,MEANCARRETN,MEANDISAUT,MEANDISFERR,MEANPENDI,MEANMDT,MEANDISN10M
0,33024,3.864110,1.981125,3.526531,8.030764,123.193442,6.490587
1,33042,2.329965,1.805417,1.399511,4.955678,229.443510,4.101466
2,24089,1.056845,0.860385,2.095330,2.267796,839.681294,2.488260
3,37274,1.455357,1.587691,2.845387,2.880397,811.855511,2.771982
4,39085,3.823505,3.933700,3.588080,5.522714,57.649513,7.050116

In [17]:
df_estructura = df_estructura.rename({'CODMUNI':'CODMUN'}, axis=1)
df_estructura

,CODMUN,MEANCARRETN,MEANDISAUT,MEANDISFERR,MEANPENDI,MEANMDT,MEANDISN10M
0,33024,3.864110,1.981125,3.526531,8.030764,123.193442,6.490587
1,33042,2.329965,1.805417,1.399511,4.955678,229.443510,4.101466
2,24089,1.056845,0.860385,2.095330,2.267796,839.681294,2.488260
3,37274,1.455357,1.587691,2.845387,2.880397,811.855511,2.771982
4,39085,3.823505,3.933700,3.588080,5.522714,57.649513,7.050116
5,39035,1.337714,1.835261,4.046212,5.888033,57.969616,1.837223
6,39075,2.736970,1.742868,1.672948,3.461595,25.932561,1.671174
7,48020,4.521363,1.417942,1.479515,12.100051,145.803400,2.593312

In [20]:
df_coordenadas = pd.read_csv("df_coordenadas.csv").iloc[:, 1:]
df_coordenadas

   CODMUN  LONGITUD_E  LATITUD_ET
0   24089   -5.567076   42.599121
1   33024   -5.659493   43.539202
2   33042   -5.707906   43.393228
3   37274   -5.665381   40.967368
4   39035   -3.414167   43.409667
5   39075   -3.809722   43.462167
6   39085   -4.042000   43.426028
7   48020   -2.923906   43.257220

In [32]:
from functools import reduce
df_list = [df_7, df_12, df_estructura, df_coordenadas]
df_merged = reduce(lambda left,right: pd.merge(left,right,on=['CODMUN'],
                   how='outer'), df_list)

In [33]:
df_merged

,CODMUN,AREAMUN,AFECBLAN,AFECGRIS,KM2BLAN,KM2GRIS,PRMUNZB,PRMUNZG,POB21_ZB,PRPZB21,...,DISTCURGH,DISTATPRIM,MEANCARRETN,MEANDISAUT,MEANDISFERR,MEANPENDI,MEANMDT,MEANDISN10M,LONGITUD_E,LATITUD_ET
0,33024,182.147589,0,0,3.507827,0,1.925816,0.000000,4799,1.76749,...,4.704072,3.419300,3.864110,1.981125,3.526531,8.030764,123.193442,6.490587,-5.659493,43.539202
1,33042,5.709173,0,0,0.331474,0,5.805987,0.000000,0,0.00000,...,2.114355,1.908441,2.329965,1.805417,1.399511,4.955678,229.443510,4.101466,-5.707906,43.393228
2,24089,39.004137,0,0,0.001086,0,0.002784,0.000000,0,0.00000,...,1.741295,1.041060,1.056845,0.860385,2.095330,2.267796,839.681294,2.488260,-5.567076,42.599121
3,37274,39.470838,0,0,0.000000,0,0.000000,0.017437,0,0.00000,...,1.861151,1.057718,1.455357,1.587691,2.845387,2.880397,811.855511,2.771982,-5.665381,40.967368
4,39085,24.582482,0,0,0.000103,0,0.000417,0.000000,0,0.00000,...,2.249691,1.682296,3.823505,3.933700,3.588080,5.522714,57.649513,7.050116,-4.042000,43.426028
5,39035,15.269803,0,0,0.037454,0,0.245279,0.000000,0,0.00000,...,1.590444,1.535823,1.337714,1.835261,4.046212,5.888033,57.969616,1.837223,-3.414167,43.409667
6,39075,36.037805,0,0,0.037648,0,0.104468,0.000000,0,0.00000,...,1.849598,0.984715,2.736970,1.742868,1.672948,3.461595,25.932561,1.671174,-3.809722,43.462167
7,48020,41.314829,0,0,0.004097,0,0.009916,0.000000,0,0.00000,...,1.605614,0.934283,4.521363,1.417942,1.479515,12.100051,145.803400,2.593312,-2.923906,43.257220

In [35]:
# Save local
df_merged.to_csv('df_estructura_completo.csv')

In [104]:
import folium as folium

In [195]:
Mad = folium.Map(location = [42.3442315,-3.7649043], zoom_start=7)
for x in range(df_merged.shape[0]):
    
    temp = pd.DataFrame(df_merged.iloc[x,:]).transpose()
    lat = float(temp["LATITUD_ET"])
    lon = float(temp["LONGITUD_E"])
    loc = [lat, lon]
    
    mystr = "<h1> Nombre del municipio </h1><br>"
    for col in temp.columns:
        mystr = mystr + "<p style=\"width:2px;height:10px;\">"  + col.upper() + ": " + str(temp[col].values[0]) + "</p>"
    
    
    iframe = folium.IFrame(html=html, width=500, height=300)
    popup = folium.Popup(iframe, max_width=2650)
    
    folium.Marker(location = loc,
                  popup = mystr,
                  tooltip = temp["CODMUN"].values[0],
                  icon = folium.Icon(icon = "fa-bicycle",
                                     prefix = 'fa',
                                     color = "white",
                                     icon_color = "lightgreen")).add_to(Mad)

Mad